// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import time "time"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// GetLongURL provides a mock function with given fields: shorturl
func (_m *Storage) GetLongURL(shorturl string) (string, error) {
	ret := _m.Called(shorturl)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(shorturl)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(shorturl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: longurl, exp
func (_m *Storage) Store(longurl string, exp time.Duration) (int64, error) {
	ret := _m.Called(longurl, exp)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, time.Duration) int64); ok {
		r0 = rf(longurl, exp)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = rf(longurl, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
