dist: trusty
language: go
go: 1.13.x
addons:
  apt:
    packages:
     - mysql-server-5.6
     - mysql-client-core-5.6
     - mysql-client-5.6
services:
  - mysql
env:
  global:
    - GO111MODULE=on
    - TEST_DSN="travis@tcp(localhost:3306)/short_url_test?parseTime=true"
  matrix:
    - TASK="make lint"
    - TASK="make test"
before_install:
  - mysql -e "DROP DATABASE IF EXISTS short_url_test; CREATE DATABASE short_url_test;"
  - make migrate_test
script:
  sh -c "$TASK"
