#!/bin/sh
ensure_docker_ip()
{
    cat .env | grep DOCKER_MACHINE_IP || echo "\nDOCKER_MACHINE_IP=$(docker-machine ip)" >> .env;
}

case $1 in
bm | build_machine)
    docker-machine create default
    eval "$(docker-machine env default)"
    ensure_docker_ip

    break;;
bi | build_image)
    docker build --tag short_url:dev .
    
    break;;
start)
    docker-compose up -d db # start db first
    docker-compose up -d --remove-orphans
    
    break;;
logs)
    docker-compose logs
    
    break;;
flush_dns)
    sudo killall -TERM mDNSResponder
    break;;
app | db | dns | nginx-proxy)
case $2 in
    shell)
        docker-compose exec $1 /bin/bash
       
        break;;
    logs)
        docker-compose logs -f $1

        break;;
    *)
    echo "unsupported service command"
    ;;
    esac;;
*)
    echo "invalid command"
    ;;
esac