#!/bin/sh
ensure_docker_ip()
{
    cat .env | grep DOCKER_MACHINE_IP || echo "\nDOCKER_MACHINE_IP=$(docker-machine ip)" >> .env;
}

case $1 in
bm | build_machine)
    docker-machine create default
    eval "$(docker-machine env default)"
    ensure_docker_ip

    break;;
bi | build_image)
    docker build --tag short_url:dev .
    
    break;;
dcp)
    docker container prune
    
    break;;
rc | refresh_containers)
    docker-compose stop
    docker-compose rm
    docker-compose up -d --remove-orphans
    break;;
flush_dns)
    sudo killall -TERM mDNSResponder
    break;;
short_url | db | dns | nginx-proxy)
case $2 in
    start)
        docker-compose exec -d $1 make run_dev
        break;;
    stop)
        docker-compose stop $1
        break;;
    shell)
        docker-compose exec $1 /bin/bash
       
        break;;
    update)
        docker-compose build $1
        docker-compose up -d $1
        
        break;;
    bootstrap)
        docker-compose run -d $1 make migrate
        
        break;;
    logs)
        docker-compose logs $1

        break;;
    esac;;
*)
    echo "No command"
    ;;
esac