// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DBAdapter is an autogenerated mock type for the DBAdapter type
type DBAdapter struct {
	mock.Mock
}

// CreateID provides a mock function with given fields:
func (_m *DBAdapter) CreateID() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpandURL provides a mock function with given fields: short
func (_m *DBAdapter) ExpandURL(short string) (string, error) {
	ret := _m.Called(short)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(short)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(short)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveURL provides a mock function with given fields: short, longURL, exp
func (_m *DBAdapter) SaveURL(short string, longURL string, exp int64) error {
	ret := _m.Called(short, longURL, exp)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int64) error); ok {
		r0 = rf(short, longURL, exp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
